### ISSUE TITLE
Bad collision handling

### ISSUE THREAD

**Issue by kozzy97** [Kinds-of-Intelligence-CFI/animal-ai#14]
I have a config like this:
```
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: 0, z: -1}
    - !Item 
      name: Wall
      positions:
      - !Vector3 {x: 7.5, y: 0, z: 20}
      - !Vector3 {x: 32.5, y: 0, z: 20}
      - !Vector3 {x: 20, y: 0, z: 7.5}
      - !Vector3 {x: 20, y: 0, z: 32.5}
      rotations: [0,0,0,0]
      sizes:
      - !Vector3 {x: 5, y: 10, z: 40}
      - !Vector3 {x: 5, y: 10, z: 40}
      - !Vector3 {x: 5, y: 10, z: 15}
      - !Vector3 {x: 5, y: 10, z: 15}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: -1, y: 0, z: -1}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
```

This is an attempt to make a smaller arena by building thick walls around the edges, and then forcing the agent to spawn at y=0 but randomly on the x-z plane.

However, occasionally, the environment will place the agent or the goal somewhere where a wall should be, and then the wall should spawn. It would be good if there was better collision handling, so objects with more specification are spawned first, and random things are spawned in between. Not sure if this will be an easy or a hard issue to fix.
