### ISSUE TITLE
Configurable Agent/Wall/Floor/Skybox Skins

### ISSUE THREAD

**Issue by alhasacademy96** [Kinds-of-Intelligence-CFI/animal-ai#24]
-------[Moved from unity-ai-repo]

It would be fantastic for the V3.0 Paper and Release to be able to configure the walls, floor, and roof of the arena to be different colours and/or textures. At the moment, you have to create walls around the edges and on the floor and roof in order to do this, which is fiddly and takes up space in the arena.

I'm imagining that the config would look something like this:

```
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 10
    t: 100
    wall_texture:
    - "picket-fence"
    floor_texture:
    - "white-noise"
    roof_texture:
    - "forest-scene"
```
Alternatively, you could pass RGB vectors to these objects and they would be solid blocks of that colour.

This would be very useful for building simple tests for simple agents (the picket fences are quite complicated). Having a range of skins (e.g., white noise, forest-scene, city-scape, etc.) could also be handy for building a narrative for human testing (e.g., "you are about to play a game where you will be an animal in a forest hunting for tasty apples...")
