### ISSUE TITLE
Configurable Arena Size

### ISSUE THREAD

**Issue by alhasacademy96** [Kinds-of-Intelligence-CFI/animal-ai#25]
-------[Moved from unity-ai-repo]

It would be good to be able to configure the size of the arena. The default can be 40x40 as it is now, but perhaps it would be good to be able to go from, say, 4x4 up to 120x120 or something (maybe infinite sized arenas for v4.0+?). It'll make the spawning coordinates trickier for the user as they'll have to bear in mind what size arena they work with, but otherwise, it'll have many use cases. For example, when training agents, it can be handy to have a small arena first, so that everything is close to everything else and they're more likely to hit a reward by chance.

I'm imagining a config like this:

```
!ArenaConfig 
arenas:
  0: !Arena
    pass_mark: 0
    t: 100
    arena_dims: [40,40]
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: 0, z: -1}
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5}
```
