### ISSUE TITLE
Multiple Arenas in a single config

### ISSUE THREAD

**Issue by kozzy97** [Kinds-of-Intelligence-CFI/animal-ai#33]
There is a problem with the experimental build when there are multiple arenas in a single file. I have tested the following config:
```
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 24}
      sizes:
      - !Vector3 { x: 2, y: 2, z: 2 }
  1: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 20, y: 0, z: 24}
      sizes:
      - !Vector3 { x: 2, y: 2, z: 2 }
  2: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 24}
      sizes:
      - !Vector3 { x: 2, y: 2, z: 2 }
```

I get only the `GoodGoalMulti` and `BadGoal` instances, not the `GoodGoal` instance when I run play.py with `v3.1.2.exp`. It works with the current stable build `v3.1.1`.
