### ISSUE TITLE
Sign Poster Boards Not Rendering

### ISSUE THREAD

**Issue by kozzy97** [Kinds-of-Intelligence-CFI/animal-ai#36]
Hi,

I was trying to build some experiments with the `SignPosterBoard` object. The following configuration does not seem to render. I have tried with `v3.1.1` and `v3.1.2.exp`. The only build that works is `v3.0.1`.

The configuration is this:

```
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent 
      positions: 
      - !Vector3 {x: 20, y: 0, z: 10} 
      rotations: [0]
      skins:
      - "panda"
    - !Item 
      name: SignPosterboard
      positions:
      - !Vector3 {x: 10, y: 0, z: 32}
      rotations: [270]
```

I've tried with a range of positions in all 3 dimensions for the signposterboard, with no luck.
