### ISSUE TITLE
frozenAgentDelays Bug

### ISSUE THREAD

**Issue by kozzy97** [Kinds-of-Intelligence-CFI/animal-ai#6]
The agent parameter `frozenAgentDelays` seems a little erratic. With the config below, it starts working well. However, after a few episodes, sometimes the agent is not frozen at all at the start and sometimes the frozen period is longer than anticipated. It seems to be especially the case when you start moving, then restart the episode by pressing `/r/`, that the agent can move almost immediately after the episode starts.

I am using the the version 3.0.1 Windows build, interacting through a Jupyter notebook in a conda env, and this issue is when you call the `AAIEnvironment` object to play as a user. I haven't tried with agent training.

Config here:
```
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 1000
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0]
      frozenAgentDelays: [10]
```
