### ISSUE TITLE
Lighting is not applied correctly to some walls

### ISSUE THREAD

**Issue by benaslater** [Kinds-of-Intelligence-CFI/animal-ai#62]
**Describe the bug**
In some configs the lighting is broken, so that certain faces of walls are completely unlit

**To Reproduce**
Play the attached config using 4.2.1 / 4.2.0

**Expected behavior**
All faces should be lit at least a bit

**Screenshots**
https://files.slack.com/files-pri/T5T7P8J1M-F08KCRK0N5V/image.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 4.2.0/4.2.1

 **Config**
```
!ArenaConfig
arenas:
  0: !Arena
    passMark: 0
    timeLimit: 450
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 18.3, y: 0, z: 19}
      - !Vector3 {x: 37, y: 0, z: 29.8}
      - !Vector3 {x: 18.0, y: 0.0, z: 33.6}
      - !Vector3 {x: 18.0, y: 0.0, z: 25.9}
      - !Vector3 {x: 3.3, y: 0.0, z: 37.0}
      - !Vector3 {x: 3.3, y: 0.0, z: 22.5}
      rotations: [0, 0, 0, 0, 0, 0]
      colors:
      - !RGB {r: 255, g: 255, b: 255}
      - !RGB {r: 255, g: 255, b: 255}
      - !RGB {r: 137, g: 137, b: 137}
      - !RGB {r: 137, g: 137, b: 137}
      - !RGB {r: 137, g: 137, b: 137}
      - !RGB {r: 137, g: 137, b: 137}
      sizes:
      - !Vector3 {x: 36.52, y: 6, z: 1}
      - !Vector3 {x: 1, y: 6, z: 20.358}
      - !Vector3 {x: 23.0, y: 0.5, z: 5.8}
      - !Vector3 {x: 23.0, y: 0.5, z: 5.8}
      - !Vector3 {x: 6.4, y: 0.5, z: 1.0}
      - !Vector3 {x: 6.4, y: 0.5, z: 1.0}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 11, y: 3.5, z: 38.5}
      sizes:
      - !Vector3 {x: 2.0, y: 2.0, z: 2.0}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 1, y: 0, z: 35}
      rotations: [90]

```
